# Generated by Django 4.2.9 on 2025-07-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for the appointment or any specific concerns.', max_length=500, null=True),
        ),
    ]
