# Generated by Django 4.2.9 on 2025-07-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointmentrequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='legacy_appointment_id',
            field=models.IntegerField(blank=True, help_text='ID of the corresponding legacy appointment for doctor confirmation', null=True),
        ),
    ]
