# Generated by Django 4.2.9 on 2024-11-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_city_profile_country_profile_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[("doctor", "Doctor"), ("patient", "Patient")],
                default="patient",
                max_length=10,
            ),
        ),
    ]
