# Generated by Django 4.2.9 on 2024-12-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('mid_low', 'Mid Low'), ('medium', 'Medium'), ('mid_high', 'Mid High'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pre_existing_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
