# Generated by Django 4.2.9 on 2025-06-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
