# Generated by Django 4.2.9 on 2025-07-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_room_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
