# Generated by Django 4.2.9 on 2025-03-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0009_medication_immunization_diagnosis"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
