# Generated by Django 4.2.9 on 2025-03-29 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0010_encounter_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labresult",
            name="report_url",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="instructions",
        ),
        migrations.AddField(
            model_name="document",
            name="encounter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="appointments.encounter",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="encounter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labresults",
                to="appointments.encounter",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="lab_results/"),
        ),
        migrations.AddField(
            model_name="prescription",
            name="duration",
            field=models.CharField(default="7 days", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="encounter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="appointments.encounter",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="encounter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnoses",
                to="appointments.encounter",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="immunization",
            name="encounter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="immunizations",
                to="appointments.encounter",
            ),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="medication",
            name="encounter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medications",
                to="appointments.encounter",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issued_prescriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
