# Generated by Django 4.2.9 on 2025-03-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0011_remove_labresult_report_url_and_more"),
        ("appointments", "XXXX_auto"),
    ]

    operations = []
