# Generated by Django 4.2.9 on 2025-03-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_user'),
        ('appointments', '0013_alter_document_file'),
    ]

    operations = [
    ]
