# Generated by Django 4.2.9 on 2025-03-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0014_merge_0001_user_0013_alter_document_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
