# Generated by Django 4.2.9 on 2025-03-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "000X_update_patient_ids"),
        ("appointments", "0015_delete_user"),
    ]

    operations = []
