# Generated by Django 4.2.9 on 2025-03-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0018_update_patient_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="temp_id",
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.CharField(
                default=None,
                editable=False,
                max_length=5,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
