# Generated by Django 4.2.9 on 2025-03-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0019_patient_temp_id_alter_patient_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
