# Generated by Django 4.2.9 on 2025-04-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0021_patient_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
    ]
